----자유게시판, 제목, 내용, 파일 , 작성자
CREATE TABLE BOARD_TBL (
    BOARD_NO NUMBER PRIMARY KEY,
    BOARD_TITLE VARCHAR2(300) NOT NULL,
    BOARD_CONTENTS VARCHAR2(2000) NOT NULL,
    BOARD_WRITER VARCHAR2(40) NOT NULL,
    BOARD_FILENAME VARCHAR2(1000),
    BOARD_FILERENAME VARCHAR2(1000),
    BOARD_COUNT NUMBER DEFAULT 0,
    B_CREATE_DATE DATE DEFAULT SYSDATE,
    B_UPDATE_DATE DATE DEFAULT SYSDATE,
    B_STATUS VARCHAR2(2) DEFAULT 'Y'
);
